config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :offers, only: :index
  get 'offers/:stamp', to: 'offers#show', as: 'offer'
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer
  attr_reader :destination_city, :total, :roundtrips, :origin_a, :origin_b,
              :date_there, :date_back, :stamp
  def initialize(args = {})
    @destination_city = args[:destination_city]
    @total = args[:total]
    @roundtrips = args[:roundtrips] # this is an array that holds two RoundTrip instances
    @origin_a = args[:origin_a]
    @origin_b = args[:origin_b]
    @date_there = args[:date_there]
    @date_back = args[:date_back]
    @stamp = generate_stamp
  end

  private

  def generate_stamp
    alphabetical = [@origin_a, @origin_b].sort
    "#{alphabetical.first}_#{alphabetical.last}_#{@destination_city}_#{@date_there}_#{@date_back}"
  end
end

app/controllers/offers_controller.rb
# Airport list: %w(PAR LON ROM MAD BER BRU VCE AMS LIS BCN MIL VIE)

class OffersController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :disable_browser_cache, only: :show
  before_action :assert_show_params, only: :show
  before_action :assert_index_params, only: :index

  def show
    options = extract_options_from_stamp(params[:stamp])
    # All offers for one route sorted by price
    @offers = Avion::SmartQPXAgent.new(options).obtain_offers.sort_by { |offer| offer.total }
    @offer = @offers[params[:start].to_i]
    # extract two arrays of roundtrips, one from each city to destination
    @trips_a = @offers.reduce([]) {|a, e| a << e.roundtrips.first }.uniq { |t| t.trip_id }
    @trips_b = @offers.reduce([]) {|a, e| a << e.roundtrips.last }.uniq { |t| t.trip_id }
    @trip_a = @trips_a[params[:left].to_i] # set the first roundtrip from city A
    @trip_b = @trips_b[params[:right].to_i] # set the second roundtrip from city B
  end

  def index
    airports = Constants::AIRPORTS.keys
    date_there = params[:date_there]
    date_back = params[:date_back]

    # generate routes
    routes = Avion.generate_triple_routes(airports, params[:origin_a], params[:origin_b])
    # Test all routes against cache
    uncached_routes = Avion.compare_routes_against_cache(routes, date_there, date_back)

    # Do we have something that is not cached?
    if uncached_routes.empty?
      # This won't do any requests as we work with cache
      @offers = get_offers_for_routes(routes, date_there, date_back)
      # clone unfiltered results to check against later
      @unfiltered_offers = @offers.clone
      # do filtering
      apply_index_filters
      # remove duplicate cities
      @offers = @offers.uniq { |offer| offer.destination_city }
      # and sort by total price
      @offers = @offers.sort_by { |offer| offer.total }
    else # we have to build a new cache
      # save url to redirect back from wait.html.erb via JS
      session[:url_for_wait] = request.original_url
      # render wait view without any routing
      render :wait
      # Send requests and build the cache in the background
      QueryRoutesJob.perform_later(uncached_routes, date_there, date_back)
    end
    session[:search_url] = request.original_url
  end

  private

  def get_offers_for_routes(routes, date_there, date_back)
    offers = []
    # This won't do any API requests at all as we work only with cache
    routes.each do |route|
      options = {
        origin_a: route.first,
        origin_b: route[1],
        destination_city: route.last,
        date_there: date_there,
        date_back: date_back
      }
      offers.concat(Avion::SmartQPXAgent.new(options).obtain_offers)
    end
    return offers
  end

  def apply_index_filters
    # set filters
    @filters = params.to_hash.slice("origin_a", "date_there", "date_back", "origin_b")

    # filter by departure time if asked
    if params["departure_time_there"].present? && params["departure_time_there"] != ""
      @filters = @filters.merge(departure_time_there: params[:departure_time_there])
      @offers = filter_by_departure_time(@offers)
    end

    #filter by arrival time if asked
    if params["arrival_time_back"].present? && params["arrival_time_back"] != ""
      @filters = @filters.merge(arrival_time_back: params[:arrival_time_back])
      @offers = filter_by_arrival_time(@offers)
    end
  end

  def assert_show_params
    # safeguard agains random urls starting with offers/
    unless params[:stamp] =~ /\w{3}_\w{3}_\w{3}_\d{4}-\d{2}-\d{2}_\d{4}-\d{2}-\d{2}/
      redirect_to root_path
      return
    end
    # Don't bother making requests if corresponding stamp not found in cache
    if $redis.get(params[:stamp]).nil?
      redirect_to root_path
      return
    end
  end

  def assert_index_params
    # if there are no query params in URL or they don't make sense - send user to home page
    if URI(request.original_url).query.blank? || params_fail?
      redirect_to root_path
      return
    end
  end

  def disable_browser_cache
    # do not cache the page to avoid caching waiting animation
    response.headers['Cache-Control'] = "no-cache, max-age=0, must-revalidate, no-store"
  end

  def extract_options_from_stamp(stamp)
    from_stamp = params[:stamp].split('_')
    {
      origin_a: from_stamp.first,
      origin_b: from_stamp[1],
      destination_city: from_stamp[2],
      date_there: from_stamp[3],
      date_back: from_stamp.last
    }
  end

  # TODO: verify if date_there is not later than date_back
  def params_fail?
    params[:origin_a].blank? || params[:origin_b].blank? || params[:date_there].blank? || params[:date_back].blank?
  end

  def departure_time_choice
    if params[:departure_time_there] == "earlybird"
      return [5,8]
    elsif params[:departure_time_there] == "morning"
      return [8,12]
    elsif params[:departure_time_there] == "afternoon"
      return [12,18]
    elsif params[:departure_time_there] == "afterwork"
      return [18,24]
    end
  end

  def arrival_time_choice
    if params[:arrival_time_back] == "earlybird"
      return [5,8]
    elsif params[:arrival_time_back] == "morning"
      return [8,12]
    elsif params[:arrival_time_back] == "afternoon"
      return [12,18]
    elsif params[:arrival_time_back] == "evening"
      return [18,24]
    end
  end

  def departure_range
    departure_as_date = Time.new(Time.parse(params[:date_there]).to_a[5],Time.parse(params[:date_there]).to_a[4],Time.parse(params[:date_there]).to_a[3])
    (departure_as_date + departure_time_choice.first.hours .. departure_as_date + departure_time_choice.last.hours)
  end

  def arrival_range
    arrival_as_date = Time.new(Time.parse(params[:date_back]).to_a[5],Time.parse(params[:date_back]).to_a[4],Time.parse(params[:date_back]).to_a[3])
    (arrival_as_date + arrival_time_choice.first.hours .. arrival_as_date + arrival_time_choice.last.hours)
  end

  def filter_by_departure_time(offers)
    offers.select { |offer|
      departure_range.include?(offer.roundtrips.first.departure_time_there) && departure_range.include?(offer.roundtrips.last.departure_time_there)
    }
  end

  def filter_by_arrival_time(offers)
    offers.select { |offer|
      arrival_range.include?(offer.roundtrips.first.arrival_time_back) && arrival_range.include?(offer.roundtrips.last.arrival_time_back)
    }
  end
end

app/helpers/offers_helper.rb
module OffersHelper
  def departure_css_class_name(filter)
    return "active" if filter == @filters[:departure_time_there]
  end

  def arrival_css_class_name(filter)
    return "active" if filter == @filters[:arrival_time_back]
  end

  def price_difference_styling(price1, price2)
    if price2 > price1
      return "#239422"
    elsif price1 > price2
      return "red"
    else
      return "black"
    end
  end

  def price_difference_text(price1, price2)
    if price2 > price1
      "Save €#{(price2 - price1).round}"
    elsif price1 > price2
      "Add €#{(price1 - price2).round}"
    else
      "Same price"
    end
  end

  def background_color_option(index)
    if index.odd?
      return "pink-background"
    end
  end
end

app/views/offers/_book_modal.html.erb
<div class="modal fade" id="<%= modal_name %>" tabindex="-1" role="dialog" aria-labelledby="<%= modal_name %>">
  <div class="modal-dialog" role="document">
    <div class="modal-content text-center">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Your booking info</h4>
      </div>
      <div class="modal-body">
        <%# FLIGHT INFO HERE %>
        <h2 style= "font-weight: lighter; color: #FF2B67">Thank you for using HALFWAY</h2>
        <p style="color: rgba(0,0,0,0.7); font-weight: lighter;">At this early stage of our project we are <strong>not yet affiliated with airlines or travel agencies</strong> so we are not quite able to book your ticket for you. This is a recap of a flight info you picked so you can make your own reservation on an airline's website or with a travel agent of your choice. We will keep this tab open in case you need another look.</p>
        <h3 style="color: black; font-weight: lighter" class="text-center">You are flying with <%= Constants::AIRLINES[trip.carrier] %></h3>
        <div class="flight-option" style= "border-top: none">
          <div class="outbound-option">
            <h2 class="text-center">Outbound on <%= trip.departure_time_there.strftime("%b %d") %></h2>
            <div class="airports-option text-center">
              <%= trip.origin_airport %> to <%= trip.destination_airport %>
              (<%= trip.flight_number_there %>)
            </div>
            <div class="hours-option text-center">
             <%= trip.departure_time_there.strftime("%H:%M") %> <i class="fa fa-plane"></i> <%= trip.arrival_time_there.strftime("%H:%M") %>
            </div>
          </div>
          <div class="return-option">
            <h2 class="text-center">Return on <%= trip.departure_time_back.strftime("%b %d") %></h2>
            <div class="airports-option text-center">
              <%= trip.destination_airport %> to
              <%= trip.origin_airport %> (<%= trip.flight_number_back %>)
            </div>
            <div class="hours-option text-center">
              <%= trip.departure_time_back.strftime("%H:%M") %> <i class="fa fa-plane"></i>
              <%= trip.arrival_time_back.strftime("%H:%M") %>
            </div>
          </div>
        </div>
        </div>
        <div class="text-center" style="padding: 10px;">
        <%= link_to "Take me to #{Constants::AIRLINES[trip.carrier]} website", Constants::AIRLINE_WEBSITES[trip.carrier], class: "btn select-button", style: "margin-top: 0", target: "_blank" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/_change_flights_modal.html.erb
<%# MODAL CHANGE FLIGHTS LEFT %>
<div class="modal fade" id="<%= modal_name %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">Choose better times</h4>
      </div>
      <div class="modal-body unpaded">
        <% trips = these_trips %>
        <% trips = trips.reject { |t| t.trip_id == this_trip.trip_id } %>
        <% trips.each_with_index do |trip, index| %>
        <div class="flight-option <%= background_color_option(index) %>">
          <div class="outbound-option">
            <h2 class="text-center">Outbound</h2>
            <div class="airports-option text-center">
              <%= trip.origin_airport  %> to <%= trip.destination_airport %>
            </div>
            <div class="hours-option text-center">
              <%= trip.departure_time_there.strftime("%H:%M") %> <i class="fa fa-plane"></i> <%= trip.arrival_time_there .strftime("%H:%M")%>
            </div>
          </div>
          <div class="return-option">
            <h2 class="text-center">Return</h2>
            <div class="airports-option text-center">
              <%= trip.destination_airport %> to
              <%= trip.origin_airport  %>
            </div>
            <div class="hours-option text-center">
              <%= trip.departure_time_back.strftime("%H:%M") %> <i class="fa fa-plane"></i>
              <%= trip.arrival_time_back.strftime("%H:%M") %>
            </div>
          </div>
          <div class="price-option text-center">
            <%= Constants::AIRLINES[trip.carrier] %>
            <p style="color: <%= price_difference_styling(trip.price,this_trip.price)%> ; padding-top: 13px; font-weight: lighter" > <%= price_difference_text(trip.price, this_trip.price) %></p>
            <h4 class="text-center">€<%= trip.price %></h4>
          </div>
          <div class="option-select text-center">
            <%= link_to controller: :offers, action: :show, right: eval(right_link), left: eval(left_link) do %>
            <button class="btn select-button">Select</button>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%# END MODAL CHANGE FLIGHT LEFT %>

app/views/offers/_flight_info.html.erb
<div class="col-xs-12 col-md-5">
  <div class="trip">
    <div class="boarding-pass">
      <header>
        <p class="logo">
          <%= Constants::AIRLINES[this_trip.carrier] %>
        </p>
        <div class="flight">
          <small>flight</small>
          <strong>
            <%= this_trip.flight_number_there %>
            <span>/</span>
            <%= this_trip.flight_number_back %></strong>
          </div>
        </header>
        <section class="cities">
          <div class="city city-left">
            <small><%= Constants::AIRPORTS[origin_city] %></small>

            <strong><%= this_trip.origin_airport %></strong>
          </div>
          <i class="fa fa-arrows-h" aria-hidden="true"></i>
          <div class="city city-right">
            <small><%= Constants::AIRPORTS[destination_city] %></small>

            <strong><%= this_trip.destination_airport %></strong>
          </div>
        </section>
        <section class="infos">
          <div class="places">
            <div class="box">
              <small class="box-title">Outbound</small>
              <strong><%= this_trip.departure_time_there.strftime("%b %d") %></strong>
            </div>
            <div class="box">
              <small>Duration</small>
              <strong><%= ((this_trip.arrival_time_there - this_trip.departure_time_there) / 60).floor%> MIN</strong>
            </div>
            <div class="box">
              <small>Departure</small>
              <strong><%= this_trip.departure_time_there.strftime("%H:%M") %></strong>
            </div>
            <div class="box">
              <small>Arrival</small>
              <strong><%= this_trip.arrival_time_there.strftime("%H:%M") %></strong>
            </div>
          </div>
          <div class="times">
            <div class="box">
              <small class="box-title">Return</small>
              <strong><%= this_trip.departure_time_back.strftime("%b %d") %></strong>
            </div>
            <div class="box">
              <small>Duration</small>
              <strong><%= ((this_trip.arrival_time_there - this_trip.departure_time_there) / 60).floor%> MIN</strong>
            </div>
            <div class="box">
              <small>Departure</small>
              <strong><%= this_trip.departure_time_back.strftime("%H:%M") %></strong>
            </div>
            <div class="box">
              <small>Arrival</small>
              <strong><%= this_trip.arrival_time_back.strftime("%H:%M") %></strong>
            </div>
          </div>
        </section>
        <section class="strap">
          <div class="box">
            <button type="button" class="btn change-flight-button" data-toggle="modal" data-target="#<%= modal_change_name %>">See other flights</button>
            <%# SOME INLINE CSS HERE %>
            <div style="font-size: 30px; width: 200px; margin: auto;"><%= this_trip.price %>€</div>
            <button type="button" class="book-button-unpadded" data-toggle="modal" data-target="#<%= modal_book_name %>">BOOK!</button>
          </section>
        </div>

      </div>
    </div>

app/views/offers/index.html.erb
<section id="main">
<header class="header_cards">
<div class="action_title text-center">
      <div class="total_date_title">
        <p> Best cities to get from <%= Constants::AIRPORTS[params[:origin_a].upcase] %> and <%= Constants::AIRPORTS[params[:origin_b].upcase] %> between <%= Date.parse(params[:date_there]).strftime("%b %d") %> and <%= Date.parse(params[:date_back]).strftime("%b %d") %></p>
      </div>
    </div>
</header>
  <div class="filters">
    <ul class="list-inline text-center">
      <li>
        <div class="text-center links-box">
        <h3><i class="fa fa-plane"></i> Departure time </h3>
        <div class="option <%= departure_css_class_name('earlybird') %>">
          <%= link_to "5-8AM", offers_path(@filters.merge(departure_time_there: "earlybird")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="option <%= departure_css_class_name('morning') %>">
          <%= link_to "8-12AM", offers_path(@filters.merge(departure_time_there: "morning")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="option <%= departure_css_class_name('afternoon') %>">
          <%= link_to "1-6PM", offers_path(@filters.merge(departure_time_there: "afternoon")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="medium-option <%= departure_css_class_name('afterwork') %>">
          <%= link_to "After 6PM", offers_path(@filters.merge(departure_time_there: "afterwork")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="longer-option <%= departure_css_class_name(nil) %>">
          <%= link_to "I don't care", offers_path(@filters.merge(departure_time_there: "")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        </div>
      </li>
      <li>
        <div class="text-center links-box return-box">
          <h3><i class="fa fa-plane"></i> Return time</h3>
        <div class="option <%= arrival_css_class_name('earlybird') %>">
          <%= link_to "5-8AM", offers_path(@filters.merge(arrival_time_back: "earlybird")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="option <%= arrival_css_class_name('morning') %>">
          <%= link_to "8-12AM", offers_path(@filters.merge(arrival_time_back: "morning")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="option <%= arrival_css_class_name('afternoon') %>">
          <%= link_to "1-6PM", offers_path(@filters.merge(arrival_time_back: "afternoon")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="medium-option <%= arrival_css_class_name('evening') %>">
          <%= link_to "After 6PM", offers_path(@filters.merge(arrival_time_back: "evening")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        <div class="longer-option <%= arrival_css_class_name(nil) %>">
          <%= link_to "I don't care", offers_path(@filters.merge(arrival_time_back: "")) , class: "radio-btn"%>
          <i class="fa fa-circle" aria-hidden="true"></i>
        </div>
        </div>
      </li>
    </ul>
  </div>
<div class="total_wrapper_cards">
  <div class="wrapper_background has-section">
    <div class="background_element"></div>
    <div class="background_element"></div>
  </div>
  <div class="home_cards_wrapper">

    <div class="container">
      <div class="row">
        <% @offers.each do |offer| %>
        <div class="col-xs-12 col-md-6">
          <div class="card_wrapper" style="background-image:
          url('<%= cl_image_path City.find_by(iata_code: offer.destination_city).card_photo.path, crop: :fill%> '); background-size: cover !important">
          <div class="card_data">
            <%# find all unfiltered roundtrips for one city %>
            <% unfiltered_for_city = @unfiltered_offers.select { |o| o.destination_city == offer.destination_city } %>
            <%# generate start param in URL based on this %>
            <%= link_to "", offer_path(offer.stamp, left: 0, right: 0, start: unfiltered_for_city.index(offer)), class: "card-link" %>
            <div class="card_content">
              <div class="card_title">
                <ul class="list-unstyled">
                  <li class="card_destination"><%= Constants::AIRPORTS[offer.destination_city]%></li>
                </ul>
                <ul class="list-unstyled">
                  <li class="card_total_price"><%= offer.total.floor %>€ <small>for 2</small></li>
                </ul>
              </div>
              <div class="card_text">
                <div class="card_text_element">
                  <p class="card_origin_city text-center" style="margin-bottom: 25px">from <%= Constants::AIRPORTS[offer.origin_a]%> <%= offer.roundtrips.first.origin_airport %></p>
                  <p class="airline text-center"> <%= Constants::AIRLINES[offer.roundtrips.first.carrier]%> </p>
                  <ul class="list-unstyled">
                    <li> Outbound <br class="hide-on-mobile"> <span style="padding-left: 6px"><%= offer.roundtrips.first.departure_time_there.strftime("%H:%M") %> <i class="fa fa-long-arrow-right"></i> <%= offer.roundtrips.first.arrival_time_there.strftime("%H:%M") %> </span> </li>
                    <li> Return <br class="hide-on-mobile"> <span style="padding-left: 29px"><%= offer.roundtrips.first.departure_time_back.strftime("%H:%M") %> <i class="fa fa-long-arrow-right"></i> <%= offer.roundtrips.first.arrival_time_back.strftime("%H:%M") %> </span> </li>
                  </ul>
                  <div class="price text-center" style= "margin-top: 25px">
                    <p><strong><%= offer.roundtrips.first.price.round %>€</strong></p>
                  </div>
                </div>
                <div class="card_text_element card_separator"></div>
                <div class="card_text_element">
                  <p class="card_origin_city text-center" style="margin-bottom: 25px">from <%= Constants::AIRPORTS[offer.origin_b] %>  <%= offer.roundtrips.last.origin_airport %></p>
                  <p class="airline text-center"> <%= Constants::AIRLINES[offer.roundtrips.last.carrier]%> </p>
                  <ul class="list-unstyled">
                    <li> Outbound <br class="hide-on-mobile"> <span style="padding-left: 6px"> <%= offer.roundtrips.last.departure_time_there.strftime("%H:%M") %> <i class="fa fa-long-arrow-right"></i> <%= offer.roundtrips.last.arrival_time_there.strftime("%H:%M") %> </span> </li>
                    <li> Return <br class="hide-on-mobile"> <span style="padding-left: 29px"> <%= offer.roundtrips.last.departure_time_back.strftime("%H:%M") %> <i class="fa fa-long-arrow-right"></i> <%= offer.roundtrips.last.arrival_time_back.strftime("%H:%M") %></span></li>
                  </ul>
                  <div class="price text-center" style= "margin-top: 25px">
                    <p><strong><%= offer.roundtrips.last.price.round %>€</strong></p>
                  </div>
                </div>
              </div>
              <div class="card_bottom"></div>
            </div>
          </div>
          </div>
        </div>
        <% end %>
        <div class="col-xs-12 col-md-6">
          <div class="card_wrapper last_card_home text-center">
            <%= link_to "", root_path, class: "card-link" %>
            <h3 >Did not find what you want? <br> Let's make a new search !</h3>
            <div class="card_data">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/offers/show.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1186058951480215";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="page-wrapper page-wrapper-trip-show">

  <div class="total_wrapper">
    <div class="wrapper_background has-section">
      <div class="background_element background-element-show"></div>
      <div class="background_element background-element-show"></div>
    </div>

    <div class="container"> <%# RESPONSIVE GRID CONTAINER %>
      <div class="row"> <%# RESPONSIVE GRID ROW %>

        <%# LEFT PART %>
        <%= render 'flight_info',
        this_trip: @trip_a,
        other_trip: @trip_b,
        origin_city: @offer.origin_a,
        destination_city: @offer.destination_city,
        modal_book_name: 'modalBookLeft',
        modal_change_name: 'modalLeft' %>
        <%# END LEFT PART %>

        <div class="col-xs-12 col-md-2">
        <div class="recap-buttons-container">
          <%= link_to session[:search_url] do %>
            <button class="other-cities-button">Another city?</button>
            <% end %>
          <div class="fb-send" data-href="<%= request.original_url %>">
          </div>
        </div>
        </div>

        <%# RIGHT PART %>
        <%= render 'flight_info',
        this_trip: @trip_b,
        other_trip: @trip_a,
        origin_city: @offer.origin_b,
        destination_city: @offer.destination_city,
        modal_book_name: 'modalBookRight',
        modal_change_name: 'modalRight' %>
        <%# END RIGHT PART %>

      </div> <%# RESPONSIVE GRID ROW END%>
    </div>  <%# RESPONSIVE GRID CONTAINER END %>


    <%# MODAL BOOK LEFT%>
    <%= render 'book_modal', trip: @trip_a, modal_name: "modalBookLeft" %>
    <%# MODAL BOOK LEFT END %>

    <%# MODAL CHANGE FLIGHTS LEFT PARTIAL%>
    <%= render 'change_flights_modal',
    these_trips: @trips_a,
    other_trips: @trips_b,
    this_trip: @trip_a,
    other_trip: @trip_b,
    right_link: '@trips_b.index(@trip_b)',
    left_link: '@trips_a.index(trip)',
    modal_name: "modalLeft" %>
    <%# MODAL CHANGE FLIGHT LEFT PARTIAL END %>

    <%# MODAL BOOK RIGHT %>
    <%= render 'book_modal', trip: @trip_b, modal_name: "modalBookRight" %>
    <%# END MODAL BOOK RIGHT %>

    <%# MODAL CHANGE FLIGHTS RIGHT PARTIAL%>
    <%= render 'change_flights_modal',
    these_trips: @trips_b,
    other_trips: @trips_a,
    this_trip: @trip_b,
    other_trip: @trip_a,
    left_link: '@trips_a.index(@trip_a)',
    right_link: '@trips_b.index(trip)',
    modal_name: "modalRight" %>
    <%# MODAL CHANGE FLIGHT RIGHT PARTIAL END %>

  </div>

app/views/offers/wait.html.erb
<div class="waiting-page-container">
  <h1>Magic is happening</h1>
  <h2 id="counter">0</h2>
  <p>Roundtrips analyzed</p>
  <div class="plane">
  <div class="wings">
    <div class="fan">
      <div class="fan-wings">
        <div class="fan-a"></div>
        <div class="fan-b"></div>
        <div class="fan-c"></div>
        <div class="fan-d"></div>
      </div>
    </div>
    <div class="cat">
      <div class="legs"></div>
    </div>
  </div>
  <div class="wheel">
    <div class="left"></div>
    <div class="right"></div>
  </div>
</div>
</div>


<%# DON'T MODIFY BELOW THIS LINE %>

<% content_for :after_js do -%>
<script>
$( document ).ready(function() {
  $('.navbar-wagon').hide()
});
</script>
<%# PUSHER STUFF %>
<script src="https://js.pusher.com/3.2/pusher.min.js"></script>
<script>
    // The document is ready for jquery
    $(function() {
      // TODO: Enable pusher logging - don't include this in production
      Pusher.logToConsole = true;

      var pusher = new Pusher('f44cd385b4d5cfdad94c', {
        cluster: 'eu',
        encrypted: true
      });

      var channel = pusher.subscribe('qpx_updates');
      var counter = 1;

      // BUG: Counter skips 1
      channel.bind('requests_completed', function(data) {
        counter += parseInt(data.roundtrips_analyzed)
        $("#counter").text(counter);
      });

      channel.bind('nonsense', function(data) {
        // use raw helper to avoid &amp in URL
        window.location = '<%= raw root_path %>';
      });

      channel.bind('done', function(data) {
        // use raw helper to avoid &amp in URL
        window.location = '<%= raw session[:url_for_wait] %>';
      });
    });
  </script>
  <% end -%>